version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: jewels/catalogapi
    build:
      context: .\ProductCatalogApi
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:7813
      DatabaseServer: mssqlserver
      DatabaseName: CatalogDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "7813:80"
    container_name: jewelscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  webmvc:
    image: events/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://eventcatalog
    ports:
      - "7811:80"
    container_name: webshop
    networks:
      - frontend
    depends_on:
      - catalog


  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1448:1433"
    container_name: jewelssqlserver
    networks:
      - backend